<?php
/**
 * Admin Panel Language Translations
 * Supported: en (English), so (Somali), ar (Arabic), fr (French)
 */

// Load language from DB if $conn is available
if (!isset($sys_lang)) {
    $sys_lang = 'en'; // default
    if (isset($conn)) {
        if (function_exists('get_setting')) {
            $sys_lang = get_setting($conn, 'language', 'en');
        } else {
            // Fallback: direct DB query
            $_lang_res = mysqli_query($conn, "SELECT setting_value FROM system_settings WHERE setting_key='language' LIMIT 1");
            if ($_lang_res && $_lang_row = mysqli_fetch_assoc($_lang_res)) {
                $sys_lang = $_lang_row['setting_value'] ?: 'en';
            }
        }
    }
}

$translations = [
    'en' => [
        // Sidebar sections
        'Overview'         => 'Overview',
        'Management'       => 'Management',
        'Intelligence'     => 'Intelligence',
        'System'           => 'System',
        // Sidebar links
        'Dashboard'        => 'Dashboard',
        'Live Tracking'    => 'Live Tracking',
        'Fleet Management' => 'Fleet Management',
        'Responder'        => 'Responder',
        'User Management'  => 'User Management',
        'Mission Logs'     => 'Mission Logs',
        'Analytics'        => 'Analytics',
        'Notifications'    => 'Notifications',
        'Reports'          => 'Reports',
        'Settings'         => 'Settings',
        // Common
        'Admin Panel'      => 'Admin Panel',
        'System Online'    => 'System Online',
        'Logout'           => 'Logout',
        'Profile'          => 'Profile',
        'Save'             => 'Save',
        'Cancel'           => 'Cancel',
        'Delete'           => 'Delete',
        'Edit'             => 'Edit',
        'Add'              => 'Add',
        'Search'           => 'Search',
        'Total'            => 'Total',
        'Status'           => 'Status',
        'Actions'          => 'Actions',
        'Name'             => 'Name',
        'Phone'            => 'Phone',
        'Email'            => 'Email',
        'Date'             => 'Date',
        'Active'           => 'Active',
        'Inactive'         => 'Inactive',
        'Available'        => 'Available',
        'On Mission'       => 'On Mission',
        'Offline'          => 'Offline',
        'Add Responder'    => 'Add Responder',
        'Total Responders' => 'Total Responders',
        'Apply Settings'   => 'Apply Settings',
        'Discard'          => 'Discard',
        'Pending SOS'      => 'Pending SOS',
        'Active Missions'  => 'Active Missions',
        'Available Units'  => 'Available Units',
        'Total Today'      => 'Total Today',
        // Settings page
        'System Configuration' => 'System Configuration',
        'Admin Dashboard Settings' => 'Admin Dashboard Settings',
        'General' => 'General',
        'Master Profile' => 'Master Profile',
        'Backups & Logs' => 'Backups & Logs',
        'General Settings' => 'General Settings',
        'Core application details used across the interface.' => 'Core application details used across the interface.',
        'Platform Name' => 'Platform Name',
        'Displayed in the header and outgoing emails.' => 'Displayed in the header and outgoing emails.',
        'Support Email Contact' => 'Support Email Contact',
        'Support Phone Number' => 'Support Phone Number',
        'Notification Delivery' => 'Notification Delivery',
        'Control automated messages and dispatch alerts.' => 'Control automated messages and dispatch alerts.',
        'Email Dispatch Summary' => 'Email Dispatch Summary',
        'Send full incident reports to admin email upon resolution.' => 'Send full incident reports to admin email upon resolution.',
        'Unit SMS Dispatch' => 'Unit SMS Dispatch',
        'Text the ambulance driver instantly when assigned to a mission.' => 'Text the ambulance driver instantly when assigned to a mission.',
        'Admin Browser Sounds' => 'Admin Browser Sounds',
        'Play acute siren ringtone locally when new SOS drops.' => 'Play acute siren ringtone locally when new SOS drops.',
        'Instance Configuration' => 'Instance Configuration',
        'Server-level parameters and synchronization behaviors.' => 'Server-level parameters and synchronization behaviors.',
        'Live Map Polling Rate' => 'Live Map Polling Rate',
        'Frequent polling provides smoother fleet tracking but increases server load.' => 'Frequent polling provides smoother fleet tracking but increases server load.',
        'System Default Language' => 'System Default Language',
        'Administrator Credentials' => 'Administrator Credentials',
        'Manage master access. Changing password logs you out immediately.' => 'Manage master access. Changing password logs you out immediately.',
        'Admin Full Name' => 'Admin Full Name',
        'Master User Email' => 'Master User Email',
        'New Master Password' => 'New Master Password',
        'Leave empty to keep current password.' => 'Leave empty to keep current password.',
        'Data Retention & Integrity' => 'Data Retention & Integrity',
        'Manage data lifecycle and archival.' => 'Manage data lifecycle and archival.',
        'Automated Daily Backup' => 'Automated Daily Backup',
        'Dumps full MySQL database into /backups directory every night.' => 'Dumps full MySQL database into /backups directory every night.',
        'Data Retention Policy' => 'Data Retention Policy',
        'Delete old incidents/tracking logs older than...' => 'Delete old incidents/tracking logs older than...',
        // Reports page
        'Reports' => 'Reports',
        '& Exports' => '& Exports',
        'From Date' => 'From Date',
        'To Date' => 'To Date',
        'All' => 'All',
        'Pending' => 'Pending',
        'Accepted' => 'Accepted',
        'Completed' => 'Completed',
        'Cancelled' => 'Cancelled',
        'Apply Filter' => 'Apply Filter',
        'Total Incidents' => 'Total Incidents',
        'Incident Log' => 'Incident Log',
        'Export CSV' => 'Export CSV',
        'Print / PDF' => 'Print / PDF',
        'Victim' => 'Victim',
        'Emergency' => 'Emergency',
        'Unit / Responder' => 'Unit / Responder',
        'Time' => 'Time',
        'Duration' => 'Duration',
        'No records found for this period.' => 'No records found for this period.',
        'Unassigned' => 'Unassigned',
        'View' => 'View',
        'Individual Reports' => 'Individual Reports',
        'Responder Reports' => 'Responder Reports',
        'All Incidents Reports' => 'All Incidents Reports',
        'Service Reports' => 'Service Reports',
        'All Dates' => 'All Dates',
        'Individual' => 'Individual',
        'Success Rate' => 'Success Rate',
        'Rejected' => 'Rejected',
        'Medical Services' => 'Medical Services',
        'Firefighter Services' => 'Firefighter Services',
        'Police Services' => 'Police Services',
        'Accident Services' => 'Accident Services',
        'Medical Info' => 'Medical Info',
        'Emergency Contacts' => 'Emergency Contacts',
        'Total Requests' => 'Total Requests',
    ],
    'so' => [
        // Sidebar sections
        'Overview'         => 'Dulmar',
        'Management'       => 'Maamulka',
        'Intelligence'     => 'Xogta',
        'System'           => 'Nidaamka',
        // Sidebar links
        'Dashboard'        => 'Xarunta Guud',
        'Live Tracking'    => 'Raadin Toos ah',
        'Fleet Management' => 'Maamulka Baabuurta',
        'Responder'        => 'Gargaariye',
        'User Management'  => 'Maamulka Isticmaalaha',
        'Mission Logs'     => 'Diiwaanka Hawlaha',
        'Analytics'        => 'Falanqaynta',
        'Notifications'    => 'Ogeysiisyada',
        'Reports'          => 'Warbixinnada',
        'Settings'         => 'Goobaha',
        // Common
        'Admin Panel'      => 'Xarunta Maamulka',
        'System Online'    => 'Nidaamka Shaqeynaya',
        'Logout'           => 'Ka Bax',
        'Profile'          => 'Xogta Shakhsiga',
        'Save'             => 'Kaydi',
        'Cancel'           => 'Jooji',
        'Delete'           => 'Tirtir',
        'Edit'             => 'Wax ka badal',
        'Add'              => 'Ku dar',
        'Search'           => 'Raadi',
        'Total'            => 'Wadarta',
        'Status'           => 'Xaalada',
        'Actions'          => 'Ficilada',
        'Name'             => 'Magaca',
        'Phone'            => 'Taleefon',
        'Email'            => 'Iimeelka',
        'Date'             => 'Taariikhda',
        'Active'           => 'Firfircoon',
        'Inactive'         => 'Aan shaqaynin',
        'Available'        => 'Diyaar ah',
        'On Mission'       => 'Hawsha ku jira',
        'Offline'          => 'Offline',
        'Add Responder'    => 'Gargaariye ku dar',
        'Total Responders' => 'Wadarta Gargaariyeyaasha',
        'Apply Settings'   => 'Kaydi Goobaha',
        'Discard'          => 'Tirtir Isbedelada',
        'Pending SOS'      => 'Gurmad Sugaya',
        'Active Missions'  => 'Hawlaha Socda',
        'Available Units'  => 'Baabuurta Diyaarka Ah',
        'Total Today'      => 'Wadarta Maanta',
        // Settings page
        'System Configuration' => 'Habaynta Nidaamka',
        'Admin Dashboard Settings' => 'Goobaha Maamulka Guud',
        'General' => 'Guud',
        'Master Profile' => 'Xogta Maamulaha',
        'Backups & Logs' => 'Kaydinta & Diiwaanka',
        'General Settings' => 'Goobaha Guud',
        'Core application details used across the interface.' => 'Xogta asaasiga ah ee nidaamka laga isticmaalo.',
        'Platform Name' => 'Magaca Nidaamka',
        'Displayed in the header and outgoing emails.' => 'Waxaa lagu soo bandhigaa dusha sare iyo iimeelada.',
        'Support Email Contact' => 'Iimeelka Taageerada',
        'Support Phone Number' => 'Taleefonka Taageerada',
        'Notification Delivery' => 'Bixinta Ogeysiisyada',
        'Control automated messages and dispatch alerts.' => 'Maamul farriimaha tooska ah iyo ogeysiisyada dirista.',
        'Email Dispatch Summary' => 'Iimeelka Warbixinta',
        'Send full incident reports to admin email upon resolution.' => 'U dir warbixin buuxda maamulaha markay hawshu dhamaato.',
        'Unit SMS Dispatch' => 'SMS-ka Baabuurta',
        'Text the ambulance driver instantly when assigned to a mission.' => 'U dir SMS darawalka markiiba marka hawl loo diro.',
        'Admin Browser Sounds' => 'Codadka Maamulaha',
        'Play acute siren ringtone locally when new SOS drops.' => 'Shid codka seeriga marka qaylo dhaan cusub (SOS) timaado.',
        'Instance Configuration' => 'Habaynta Adeegga',
        'Server-level parameters and synchronization behaviors.' => 'Goobaha server-ka iyo habdhaqanka is-waafajinta.',
        'Live Map Polling Rate' => 'Xawaaraha Khariidada',
        'Frequent polling provides smoother fleet tracking but increases server load.' => 'U fiirinta dhakhsaha badan waxay sahlaysaa dabagalka baabuurta balse culays ayay saartaa server-ka.',
        'System Default Language' => 'Luuqadda Nidaamka',
        'Administrator Credentials' => 'Aqoonsiga Maamulaha',
        'Manage master access. Changing password logs you out immediately.' => 'Maamul gelitaanka. Beddelida furaha waxay kaa saaraysaa nidaamka markiiba.',
        'Admin Full Name' => 'Magaca Maamulaha oo Buuxa',
        'Master User Email' => 'Iimeelka Maamulaha',
        'New Master Password' => 'Fure Cusub',
        'Leave empty to keep current password.' => 'Banaan kaga tag haddii aadan rabin inaad beddesho furaha.',
        'Data Retention & Integrity' => 'Kaydinta & Badbaadada Xogta',
        'Manage data lifecycle and archival.' => 'Maamul nolosha xogta iyo kaydkeeda.',
        'Automated Daily Backup' => 'Kaydinta Tooska ah Ee Maalinlaha ah',
        'Dumps full MySQL database into /backups directory every night.' => 'Waxay kaydisaa dhamaan xogta MySQL habeen kasta.',
        'Data Retention Policy' => 'Sharciga Haynta Xogta',
        'Delete old incidents/tracking logs older than...' => 'Tirtir dhacdooyinkii hore/xogtii la raad-raacay oo ka weyn...',
        // Reports page
        'Reports' => 'Warbixinnada',
        '& Exports' => '& Dhoofinta',
        'From Date' => 'Laga bilaabo',
        'To Date' => 'Ilaa taariikh',
        'All' => 'Dhammaan',
        'Pending' => 'Sugaya',
        'Accepted' => 'La aqbalay',
        'Completed' => 'Dhamaaday',
        'Cancelled' => 'La joojiyay',
        'Apply Filter' => 'Raadi',
        'Total Incidents' => 'Wadarta Dhacdooyinka',
        'Incident Log' => 'Diiwaanka Dhacdooyinka',
        'Export CSV' => 'Dhoofi CSV',
        'Print / PDF' => 'Daabac / PDF',
        'Victim' => 'Bukaanka',
        'Emergency' => 'Xaaladda',
        'Unit / Responder' => 'Baabuurka / Gargaaraha',
        'Time' => 'Waqtiga',
        'Duration' => 'Muddada',
        'No records found for this period.' => 'Wax xog ah laguma helin xilligan.',
        'Unassigned' => 'Aan la dirin',
        'View' => 'Eeg',
        'Individual Reports' => 'Warbixinnada Shakhsiga',
        'Responder Reports' => 'Warbixinnada Gargaarayaasha',
        'All Incidents Reports' => 'Warbixinnada Dhacdooyinka',
        'Service Reports' => 'Warbixinnada Adeegyada',
        'All Dates' => 'Dhamaan Taariikhaha',
        'Individual' => 'Shakhsiga',
        'Success Rate' => 'Boqolleyda Guusha',
        'Rejected' => 'La Diaday',
        'Medical Services' => 'Adeegga Caafimaadka',
        'Firefighter Services' => 'Adeegga Dabdamiska',
        'Police Services' => 'Adeegga Boliiska',
        'Accident Services' => 'Adeegga Shilalka',
        'Medical Info' => 'Xogta Caafimaadka',
        'Emergency Contacts' => 'Taleefannada Gurmadka',
        'Total Requests' => 'Wadarta Dalabka',
    ],
    'ar' => [
        // Sidebar sections
        'Overview'         => 'نظرة عامة',
        'Management'       => 'الإدارة',
        'Intelligence'     => 'الذكاء',
        'System'           => 'النظام',
        // Sidebar links
        'Dashboard'        => 'لوحة التحكم',
        'Live Tracking'    => 'التتبع المباشر',
        'Fleet Management' => 'إدارة الأسطول',
        'Responder'        => 'المستجيب',
        'User Management'  => 'إدارة المستخدمين',
        'Mission Logs'     => 'سجلات المهام',
        'Analytics'        => 'التحليلات',
        'Notifications'    => 'الإشعارات',
        'Reports'          => 'التقارير',
        'Settings'         => 'الإعدادات',
        // Common
        'Admin Panel'      => 'لوحة الإدارة',
        'System Online'    => 'النظام متصل',
        'Logout'           => 'تسجيل خروج',
        'Profile'          => 'الملف الشخصي',
        'Save'             => 'حفظ',
        'Cancel'           => 'إلغاء',
        'Delete'           => 'حذف',
        'Edit'             => 'تعديل',
        'Add'              => 'إضافة',
        'Search'           => 'بحث',
        'Total'            => 'المجموع',
        'Status'           => 'الحالة',
        'Actions'          => 'الإجراءات',
        'Name'             => 'الاسم',
        'Phone'            => 'الهاتف',
        'Email'            => 'البريد الإلكتروني',
        'Date'             => 'التاريخ',
        'Active'           => 'نشط',
        'Inactive'         => 'غير نشط',
        'Available'        => 'متاح',
        'On Mission'       => 'في مهمة',
        'Offline'          => 'غير متصل',
        'Add Responder'    => 'إضافة مستجيب',
        'Total Responders' => 'إجمالي المستجيبين',
        'Apply Settings'   => 'تطبيق الإعدادات',
        'Discard'          => 'تجاهل',
        'Pending SOS'      => 'طلبات معلقة',
        'Active Missions'  => 'مهام نشطة',
        'Available Units'  => 'الوحدات المتاحة',
        'Total Today'      => 'المجموع اليوم',
        // Settings page
        'System Configuration' => 'تكوين النظام',
        'Admin Dashboard Settings' => 'إعدادات لوحة تحكم الإدارة',
        'General' => 'عام',
        'Master Profile' => 'الملف الشخصي الرئيسي',
        'Backups & Logs' => 'النسخ الاحتياطية والسجلات',
        'General Settings' => 'الإعدادات العامة',
        'Core application details used across the interface.' => 'تفاصيل التطبيق الأساسية المستخدمة عبر الواجهة.',
        'Platform Name' => 'اسم المنصة',
        'Displayed in the header and outgoing emails.' => 'معروض في الترويسة ورسائل البريد الإلكتروني الصادرة.',
        'Support Email Contact' => 'البريد الإلكتروني للدعم',
        'Support Phone Number' => 'رقم هاتف الدعم',
        'Notification Delivery' => 'توصيل الإشعارات',
        'Control automated messages and dispatch alerts.' => 'التحكم في الرسائل الآلية وتنبيهات الإرسال.',
        'Email Dispatch Summary' => 'ملخص إرسال البريد الإلكتروني',
        'Send full incident reports to admin email upon resolution.' => 'إرسال تقارير الحوادث الكاملة إلى بريد المشرف عند الحل.',
        'Unit SMS Dispatch' => 'إرسال رسائل قصيرة للوحدة',
        'Text the ambulance driver instantly when assigned to a mission.' => 'إرسال رسالة نصية لسائق سيارة الإسعاف فوراً عند تكليفه بمهمة.',
        'Admin Browser Sounds' => 'أصوات متصفح المشرف',
        'Play acute siren ringtone locally when new SOS drops.' => 'تشغيل نغمة إنذار حادة محليًا عند وصول نداء استغاثة جديد.',
        'Instance Configuration' => 'تكوين الخادم',
        'Server-level parameters and synchronization behaviors.' => 'معلمات مستوى الخادم وسلوكيات المزامنة.',
        'Live Map Polling Rate' => 'معدل تحديث الخريطة الحية',
        'Frequent polling provides smoother fleet tracking but increases server load.' => 'التحديث المتكرر يوفر تتبعًا أكثر سلاسة للأسطول ولكنه يزيد من حمل الخادم.',
        'System Default Language' => 'لغة النظام الافتراضية',
        'Administrator Credentials' => 'بيانات اعتماد المسؤول',
        'Manage master access. Changing password logs you out immediately.' => 'إدارة الوصول الرئيسي. تغيير كلمة المرور يسجلك خروجاً على الفور.',
        'Admin Full Name' => 'الاسم الكامل للمشرف',
        'Master User Email' => 'البريد الإلكتروني للمستخدم الرئيسي',
        'New Master Password' => 'كلمة مرور رئيسية جديدة',
        'Leave empty to keep current password.' => 'اتركه فارغًا للاحتفاظ بكلمة المرور الحالية.',
        'Data Retention & Integrity' => 'الاحتفاظ بالبيانات وسلامتها',
        'Manage data lifecycle and archival.' => 'إدارة دورة حياة البيانات والأرشفة.',
        'Automated Daily Backup' => 'نسخ احتياطي يومي آلي',
        'Dumps full MySQL database into /backups directory every night.' => 'يقوم بتفريغ قاعدة بيانات MySQL بالكامل في دليل /backups كل ليلة.',
        'Data Retention Policy' => 'سياسة الاحتفاظ بالبيانات',
        'Delete old incidents/tracking logs older than...' => 'حذف الحوادث/سجلات التتبع القديمة الأقدم من...',
        // Reports page
        'Reports' => 'التقارير',
        '& Exports' => 'والصادرات',
        'From Date' => 'من تاريخ',
        'To Date' => 'إلى تاريخ',
        'All' => 'الكل',
        'Pending' => 'قيد الانتظار',
        'Accepted' => 'مقبول',
        'Completed' => 'مكتمل',
        'Cancelled' => 'ملغى',
        'Apply Filter' => 'تطبيق الفلتر',
        'Total Incidents' => 'إجمالي الحوادث',
        'Incident Log' => 'سجل الحوادث',
        'Export CSV' => 'تصدير CSV',
        'Print / PDF' => 'طباعة / PDF',
        'Victim' => 'الضحية',
        'Emergency' => 'الطوارئ',
        'Unit / Responder' => 'الوحدة / المستجيب',
        'Time' => 'الوقت',
        'Duration' => 'المدة',
        'No records found for this period.' => 'لا توجد سجلات لهذه الفترة.',
        'Unassigned' => 'غير معين',
        'View' => 'عرض',
    ],
    'fr' => [
        // Sidebar sections
        'Overview'         => 'Aperçu',
        'Management'       => 'Gestion',
        'Intelligence'     => 'Intelligence',
        'System'           => 'Système',
        // Sidebar links
        'Dashboard'        => 'Tableau de bord',
        'Live Tracking'    => 'Suivi en direct',
        'Fleet Management' => 'Gestion de flotte',
        'Responder'        => 'Intervenant',
        'User Management'  => 'Gestion des utilisateurs',
        'Mission Logs'     => 'Journaux de mission',
        'Analytics'        => 'Analytique',
        'Notifications'    => 'Notifications',
        'Reports'          => 'Rapports',
        'Settings'         => 'Paramètres',
        // Common
        'Admin Panel'      => 'Panneau Admin',
        'System Online'    => 'Système en ligne',
        'Logout'           => 'Déconnexion',
        'Profile'          => 'Profil',
        'Save'             => 'Enregistrer',
        'Cancel'           => 'Annuler',
        'Delete'           => 'Supprimer',
        'Edit'             => 'Modifier',
        'Add'              => 'Ajouter',
        'Search'           => 'Rechercher',
        'Total'            => 'Total',
        'Status'           => 'Statut',
        'Actions'          => 'Actions',
        'Name'             => 'Nom',
        'Phone'            => 'Téléphone',
        'Email'            => 'Email',
        'Date'             => 'Date',
        'Active'           => 'Actif',
        'Inactive'         => 'Inactif',
        'Available'        => 'Disponible',
        'On Mission'       => 'En mission',
        'Offline'          => 'Hors ligne',
        'Add Responder'    => 'Ajouter un intervenant',
        'Total Responders' => 'Total des intervenants',
        'Apply Settings'   => 'Appliquer les paramètres',
        'Discard'          => 'Annuler',
        'Pending SOS'      => 'SOS en attente',
        'Active Missions'  => 'Missions actives',
        'Available Units'  => 'Unités disponibles',
        'Total Today'      => 'Total aujourd\'hui',
        // Settings page
        'System Configuration' => 'Configuration du système',
        'Admin Dashboard Settings' => 'Paramètres du tableau de bord Admin',
        'General' => 'Général',
        'Master Profile' => 'Profil principal',
        'Backups & Logs' => 'Sauvegardes et journaux',
        'General Settings' => 'Paramètres généraux',
        'Core application details used across the interface.' => 'Détails de base de l\'application.',
        'Platform Name' => 'Nom de la plateforme',
        'Displayed in the header and outgoing emails.' => 'Affiché dans l\'en-tête et les emails sortants.',
        'Support Email Contact' => 'Email de contact du support',
        'Support Phone Number' => 'Numéro de téléphone du support',
        'Notification Delivery' => 'Livraison des notifications',
        'Control automated messages and dispatch alerts.' => 'Contrôler les messages automatisés et les alertes de répartition.',
        'Email Dispatch Summary' => 'Résumé des envois par email',
        'Send full incident reports to admin email upon resolution.' => 'Envoyer des rapports d\'incidents complets par email.',
        'Unit SMS Dispatch' => 'Envoi de SMS à l\'unité',
        'Text the ambulance driver instantly when assigned to a mission.' => 'Envoyer un SMS au chauffeur de l\'ambulance instantanément.',
        'Admin Browser Sounds' => 'Sons du navigateur Admin',
        'Play acute siren ringtone locally when new SOS drops.' => 'Jouer une sonnerie de sirène localement.',
        'Instance Configuration' => 'Configuration de l\'instance',
        'Server-level parameters and synchronization behaviors.' => 'Paramètres au niveau du serveur.',
        'Live Map Polling Rate' => 'Taux de rafraîchissement de la carte',
        'Frequent polling provides smoother fleet tracking but increases server load.' => 'Un rafraîchissement fréquent augmente la charge du serveur.',
        'System Default Language' => 'Langue par défaut du système',
        'Administrator Credentials' => 'Identifiants de l\'administrateur',
        'Manage master access. Changing password logs you out immediately.' => 'Gérer l\'accès principal. Le changement de mot de passe vous déconnecte.',
        'Admin Full Name' => 'Nom complet de l\'admin',
        'Master User Email' => 'Email de l\'utilisateur principal',
        'New Master Password' => 'Nouveau mot de passe',
        'Leave empty to keep current password.' => 'Laisser vide pour conserver le mot de passe actuel.',
        'Data Retention & Integrity' => 'Rétention et intégrité des données',
        'Manage data lifecycle and archival.' => 'Gérer le cycle de vie et l\'archivage des données.',
        'Automated Daily Backup' => 'Sauvegarde quotidienne automatisée',
        'Dumps full MySQL database into /backups directory every night.' => 'Sauvegarde la base de données MySQL toutes les nuits.',
        'Data Retention Policy' => 'Politique de rétention des données',
        'Delete old incidents/tracking logs older than...' => 'Supprimer les anciens incidents plus vieux que...',
        // Reports page
        'Reports' => 'Rapports',
        '& Exports' => '& Exportations',
        'From Date' => 'Date de début',
        'To Date' => 'Date de fin',
        'All' => 'Tout',
        'Pending' => 'En attente',
        'Accepted' => 'Accepté',
        'Completed' => 'Terminé',
        'Cancelled' => 'Annulé',
        'Apply Filter' => 'Appliquer le filtre',
        'Total Incidents' => 'Total des incidents',
        'Incident Log' => 'Journal des incidents',
        'Export CSV' => 'Exporter CSV',
        'Print / PDF' => 'Imprimer / PDF',
        'Victim' => 'Victime',
        'Emergency' => 'Urgence',
        'Unit / Responder' => 'Unité / Intervenant',
        'Time' => 'Temps',
        'Duration' => 'Durée',
        'No records found for this period.' => 'Aucun enregistrement trouvé pour cette période.',
        'Unassigned' => 'Non assigné',
        'View' => 'Voir',
    ],
];

/**
 * Translate a string based on the current language.
 */
function t($key) {
    global $translations, $sys_lang;
    $lang = $sys_lang ?? 'en';
    if (isset($translations[$lang][$key])) {
        return $translations[$lang][$key];
    }
    // Fallback to English
    if (isset($translations['en'][$key])) {
        return $translations['en'][$key];
    }
    return $key;
}
?>
