import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';

/// Global App Translator
/// Usage in any widget: AppTranslator.t(context, 'Dashboard')
class AppTranslator {
  // ─── Somali Translations ───────────────────────────────────────────────────
  static const Map<String, String> _so = {
    // Navigation & Drawer
    'Dashboard': 'Xarunta Guud',
    'Medical ID': 'Aqoonsiga Caafimaadka',
    'Contacts': 'Xiriiriyayaasha',
    'History': 'Taariikh',
    'My Account': 'Xisaabteena',
    'Settings': 'Habeeynta',
    'Sign Out': 'Ka Bax',
    'MAIN': 'HORENA',
    'ACCOUNT': 'XISAABTA',
    'EDIT PROFILE PICTURE': 'BEDEL SAWIRKA',
    'SOS': 'SOS',
    'Map': 'Khariidad',
    'Proof': 'Caddayn',
    'Community': 'Bulshada',
    'More': 'Dheeraad',

    // Home Screen
    'Emergency Center': 'Xarunta Xaaladaha Degdegga',
    'Send SOS': 'Dir SOS',
    'TAP ONCE TO SEND ALERT': 'RIIX SI AAD U DIRTO OGEYSIISKA',
    'Hold to Cancel Alert': 'Haya si aad u joojiso ogeysiiska',
    'Sending Emergency Signal...': 'Diraya Calaamadda Degdegga...',
    'SOS Alert Activated': 'SOS Ogeysiiska Waa La Hawlgeliyey',
    'Responders are viewing your location. Stay calm.':
        'Gurmadku wuxuu eegayaa goobtagaaga. Xalaasnow.',
    'ACTIVE SOS': 'SOS FIRFIRCOON',
    'Emergency Type': 'Nooca Xaaladda',
    'Medical': 'Caafimaad',
    'Fire': 'Dab',
    'Accident': 'Shil',
    'Security': 'Amaan',
    'Other': 'Kale',
    'Cancel': 'Jooji',
    'Cancel Request': 'Jooji Codsiga',
    'Pending': 'Sugaya',
    'Accepted': 'La Aqbalay',
    'En Route': 'Socda',
    'Arrived': 'Soo Gaaray',
    'Completed': 'Dhammaystay',
    'Driver Assigned': 'Darawal Loo Xilsaaray',
    'Call Driver': 'Wac Darawalka',
    'Track on Map': 'Ku Raac Khariidadda',
    'View Timeline': 'Arag Jadwalka',
    'Emergency Contacts': 'Xiriiriyayaasha Degdegga',
    'EMERGENCY CONTACTS': 'XIRIIRIYAYAASHA DEGDEGGA',
    'Guardian network': 'Shabakadda ilaalinta',
    'TOTAL SOS SENT': 'WADARTA SOS LA DIRAY',
    'All time': 'Waqti kasta',
    'LAST EMERGENCY': 'GURMADKII UGU DAMBEEYAY',
    'Most recent': 'Ugu dambeeyay',
    'SELECT EMERGENCY TYPE': 'DOORO NOOCA XAALADDA DEGDEG GA AH',
    'AMBULANCE': 'GAARIGA GURMADKA (AMBULANCE)',
    'Medical Emergency': 'Xaalad Degdeg ah oo Caafimaad',
    'FIRE RESCUE': 'DAB-DAMISKA',
    'Fire & Burns': 'Dab & Gubasho',
    'POLICE': 'BOOLISKA',
    'Security Help': 'Caawinaad Dhanka Amniga',
    'ACCIDENT': 'SHILKA',
    'Vehicle Crash': 'Shil Gaari',
    'ACTION GUIDE': 'TILMAAMAHA WAXQABADKA',
    '🚑 Stay calm. Check for breathing. If bleeding, apply firm pressure. Do not move if head/neck injury suspected.': '🚑 Daji naftaada. Hubi neefsashada. Haddii uu dhiig baxayo, si adag u cadaadi. Ha dhaqaajin haddii laga shakiyo dhaawac madaxa/luqunta ah.',
    '🚒 Evacuate immediately. Stay low under smoke. Do not open hot doors. Dial emergency services immediately.': '🚒 Ka bax goobta isla markiiba. Hoos isku dhig qiiqa hoostiisa. Ha furin albaabada kulul. Wac adeegyada degdegga ah isla markiiba.',
    '👮 Seek immediate shelter. Lock doors and windows. Stay quiet and turn off lights. Wait for police arrival.': '👮 Raadso magangalyo isla markiiba. Quful albaabada iyo daaqadaha. Aamusnaan ku jiro oo dami iftiinka. Sug imaanshaha booliska.',
    '🚗 Pull over to a safe area. Turn on hazard lights. Check for injuries. Do not move severely injured persons unless necessary.': '🚗 U leexi meel nabdoon. Daar nalalka digniinta (hazards). Hubi dhaawacyada. Ha dhaqaajin dadka aadka u dhaawacan ilaa ay lagama maarmaan noqoto.',
    '🚨 Stay calm. Check for safety. Report location immediately to emergency responders.': '🚨 Daji naftaada. Hubi badbaadada. U sheeg goobtaada isla markiiba kooxda gurmadka.',
    'GPS ACCURACY': 'SAXNAANTA GPS-KA',
    '📡 Good signal': '📡 Signal fiican',
    'Safety: Good': 'Amniga: Wanaagsan',
    'GPS Good': 'GPS Wanaagsan',
    'EMERGENCY BROADCAST ACTIVE': 'GURMADKA WAA FIRFIRCOON YAHAY',
    'TAP BUTTON TO TRIGGER SOS': 'TAABO BADHANKA SI AAD U DIRTO SOS',
    'Online': 'Khadka ku jira',
    'Hello': 'Haye',
    'User': 'Isticmaale',
    'RESPONSE TIMELINE': 'JADWALKA JAWAABTA',
    'Emergency signal broadcast': 'Baahinta calaamada SOS',
    'Dispatched': 'Loo Diray',
    'Dispatch center notified': 'Xarunta dirista waa la ogeysiiyey',
    'Team Assigned': 'Koox Loo Xilsaaray',
    'Rescue unit selected': 'Gaariga gurmadka waa la doortay',
    'On The Way': 'Jidka ku jira',
    'Team heading to location': 'Kooxda waxay ku socotaa goobta',
    'Team on scene': 'Kooxda waxay joogtaa goobta',
    'Emergency successfully resolved': 'Xaalada degdega ah si guul leh ayaa loo xaliyey',
    'No contacts': 'Xiriiriye ma jiro',
    'contacts': 'xiriiriyo',

    // Contacts Screen
    'GUARDIAN NETWORK': 'SHABAKADDA ILAALINTA',
    'Add Contact': 'Ku Dar Xiriiriye',
    'No emergency contacts yet.': 'Xiriiriye degdeg ah ma jiro weli.',
    'Add contacts to notify loved ones in an emergency.':
        'Ku dar xiriiriyayaasha si loogu ogeysiiso ehelkaaga xaaladda degdegga ah.',
    'Name': 'Magaca',
    'Phone': 'Telefoon',
    'Family Relationship': 'Xiriirka Qoyska',
    'Save': 'Keydi',
    'Edit': 'Wax Ka Beddel',
    'Delete': 'Tirtir',
    'Please fill all fields': 'Fadlan buuxi dhammaan meelaha',

    // Medical Screen
    'Medical & Safety Info': 'Xogta Caafimaadka & Ammaanka',
    'Blood Type': 'Nooca Dhiigga',
    'Allergies': 'Xasaasiyadaha',
    'Medical Conditions': 'Xaaladaha Caafimaad',
    'Current Medications': 'Daawada Hadda',
    'Emergency Notes': 'Xusuus-qorka Degdegga',
    'Save Changes': 'Keydi Isbedelada',
    'Saving...': 'Keydinaya...',
    'MEDICAL RECORDS': 'XOGTA CAAFIMAADKA',
    'Medical Identity Card': 'Aqoonsiga Caafimaadka',
    'Medical ID Saved Successfully!': 'Aqoonsiga Caafimaadka waa la keydiyay!',
    'Failed to save Medical ID': 'Waa uu guuldareystay keydinta Aqoonsiga Caafimaadka',
    'Volunteer as a Blood Donor': 'Isu qor ku deeqida dhiigga',
    'Your name, blood group, and contact will be visible to the community in emergencies.': 'Magacaaga, nooca dhiiggaaga, iyo xiriirkaaga waxay u muuqan doonaan bulshada xilliyada xaaladaha degdegga ah.',

    // History Screen
    'Rescue History': 'Taariikhda Gurmadka',
    'No rescue history yet.': 'Taariikh gurmad ah ma jiro weli.',
    'Your past SOS requests will appear here.':
        'Codsigaadii SOS-ka ee hore waa ka soo muuqan doonaan halkan.',
    'Status': 'Xaalad',
    'Date': 'Taariikhda',
    'Type': 'Nooca',
    'RECORDS': 'TAARIICHO',
    'Details': 'Faahfaahin',
    'Driver': 'Darawal',
    'Waiting for responder...': 'Sugaya gurmad...',
    'Cancel Emergency?': 'Jooji Gurmadka?',
    'Are you sure you want to cancel this emergency request?': 'Ma hubtaa inaad rabto inaad joojiso codsiga gurmadka?',
    'NO, STAY ACTIVE': 'MAYA, SII WAD FIRFIRCOONIDA',
    'YES, CANCEL': 'HAA, JOOJI',
    'CANCEL EMERGENCY': 'JOOJI GURMADKA',
    'TRACK DRIVER ON MAP': 'KU LA SOCO DARAWALKA KHARIIDADDA',
    'EMERGENCY COMMAND CENTER': 'XARUNTA GURMADKA DEGDEGGA AH',
    'WELCOME': 'Soo Dhawoow',

    // Safety Check Dialog
    'Are You Safe?': 'Ma Nabad Qabtaa?',
    "We detected unusual inactivity. Please confirm you're okay or trigger an emergency SOS.":
        "Waxaan ogaanay dhaqdhaqaaq la'aan aan caadi ahayn. Fadlan xaqiiji inaad nabad tahay ama dir SOS degdeg ah.",
    "I'm Safe": "Nabad Baan Ahay",
    'Status Noted': 'Xaaladda Waa La Diiwangeliyey',
    'Glad to hear you are safe. We continue monitoring.':
        'Aad baan ugu faraxsanahay inaad nabad tahay. Sii wadaynaa la socodka.',


    // Notifications Screen
    'Alert Notifications': 'Ogeysiisyada Digniinta',
    'Notifications': 'Ogeysiisyada',
    'No notifications yet.': 'Ogeysiis ma jiro weli.',
    'Mark all as read': 'Dhammaantood u calaamadee mid la akhristay',
    'Delete Notification': 'Tirtir Ogeysiiska',
    'Are you sure you want to delete this notification?':
        'Ma hubtaa inaad rabto inaad tirtirto ogeysiiskaan?',
    'Notification deleted successfully!': 'Ogeysiiska waa la tirtiray!',
    'Failed to delete notification': 'Waa uu guuldareystay tirtiridda ogeysiiska.',
    'Error': 'Cillad',
    'No notifications': 'Ma jiraan ogeysiisyo',
    'Updates about your rescue will appear here.': 'Wixii cusbooneysiin ah oo ku saabsan\ngurmadkaaga halkan ayaad ku arki doontaa.',
    'Pull down to refresh': 'Kor u jiid si aad u cusbooneysiiso',
    'Refresh': 'Cusbooneysiinta',
    'No notifications now!': 'Ma jiraan ogeysiisyo hadda!',
    'Any updates will be shown here.': 'Wixii cusbooneysiin ah halkan ayaad ku arki doontaa.',
    'Notifications Count': 'Ogeysiis',
    'Just now': 'Hadda',
    'ago': 'ka hor',
    'minutes': 'daqiiqo',
    'hours': 'saacadood',
    'days': 'maalmood',

    // Profile Screen
    'User Settings': 'Habaynta Isticmaalaha',
    'Edit Profile': 'Wax Ka Beddel Xisaabta',
    'Full Name': 'Magaca Buuxa',
    'Email Address': 'Cinwaanka Emailka',
    'Phone Number': 'Numberka Telefoonka',
    'Gender': 'Jinsiga',
    'Date of Birth': 'Taariikhda Dhalashada',
    'Change Password': 'Beddel Fuurka Sirta',
    'Delete Account': 'Tirtir Xisaabta',
    'Current Password': 'Fuurka Sirta Hadda',
    'New Password': 'Fuurka Sirta Cusub',
    'Confirm Password': 'Xaqiiji Fuurka Sirta',
    'Update Profile': 'Cusboonaysii Xisaabta',
    'Male': 'Lab',
    'Female': 'Dheddig',
    'Manage your profile, security, and account preferences.': 'Maamul profile-kaaga, amaankaaga, iyo dooqyadaada.',
    'VERIFIED USER': 'ISTICMAALE LA XAQIIJIYAY',
    'Update your personal information': 'Cusbooneysii macluumaadkaaga gaarka ah',
    'Enter full name': 'Geli magaca buuxa',
    'Enter phone number': 'Geli numberka telefoonka',
    'Enter email address': 'Geli cinwaanka emailka',
    'All fields are required!': 'Dhammaan meelaha waa khasab!',
    'Name and phone are required!': 'Magaca iyo lambarka telefoonka waa khasab!',
    '✅ Profile updated successfully!': '✅ Profile-ka waa la cusbooneysiiyay!',
    'Failed to update profile': 'Waa uu guuldareystay cusbooneysiinta profile-ka',
    'Change your account password': 'Beddel fuurka sirta ah ee xisaabtaada',
    'Enter current password': 'Geli fuurka sirta hadda',
    'Min. 8 characters': 'Ugu yaraan 8 xaraf',
    'Repeat new password': 'Ku celi fuurka sirta cusub',
    'Update Password': 'Cusbooneysii Fuurka Sirta',
    'Please fill in all password fields!': 'Fadlan buuxi dhammaan meelaha fuurka sirta!',
    'New password must be at least 8 characters!': 'Fuurka sirta cusub waa inuu ka koobnaadaa ugu yaraan 8 xaraf!',
    'New passwords do not match!': 'Fuurka sirta cusub ma isku mid aha!',
    'Password updated successfully!': 'Fuurka sirta waa la cusbooneysiiyay!',
    'Failed to update password': 'Waa uu guuldareystay cusbooneysiinta fuurka sirta',
    'Location Info': 'Xogta Goobta',
    'Your GPS and location access status': 'Xaaladda GPS-ka iyo helitaanka goobta',
    'Last Known Location': 'Goobtii Ugu Dambeysay',
    '✅ Location enabled successfully.': '✅ Goobta waa la daaray.',
    'Location disabled.': 'Goobtii waa la damiyay.',
    'Failed to update Location': 'Waa uu guuldareystay cusbooneysiinta goobta',
    '⚠️ GPS enabled in settings, but browser/device permission is denied.': '⚠️ GPS waa la daaray, laakiin ogolaanshaha qalabka waa la diiday.',
    '⚠️ GPS enabled in settings, but location services are unavailable.': '⚠️ GPS waa la daaray, laakiin adeegga goobta ma shaqaynayo.',
    '✅ Live location streaming enabled during SOS.': '✅ Wadaagista goobta tooska ah waa la daaray.',
    'Live location streaming disabled.': 'Wadaagista goobta tooska ah waa la damiyay.',
    'Failed to update Live Location preference': 'Waa uu guuldareystay beddelista dooqyada goobta',
    'Danger Zone': 'Khatarta Xisaabta',
    'Irreversible account actions': 'Waxqabadyo aan dib loo celin karin',
    'All your data, history, and records will be permanently removed. This action cannot be undone.': 'Dhammaan xogtaada, taariikhdaada, iyo records-kaaga si joogto ah ayaa loo tirtiri doonaa. Tallaabadan dib looma celin karo.',
    'Are you absolutely sure you want to delete your account? This action cannot be undone.': 'Ma hubtaa inaad rabto inaad tirtirto xisaabtaada? Tallaabadan dib looma celin karo.',
    'Please enter your password': 'Fadlan geli fuurkaaga sirta ah',
    'Failed to delete account': 'Waa uu guuldareystay tirtiridda xisaabta',

    // Map Screen
    'Live Tracking': 'La-Socoshada Tooska ah',
    'Driver Location': 'Goobta Darawalka',
    'Your Location': 'Goobtagaaga',
    'Loading map...': 'Khariidadda waa la rarayo...',
    'ETA': 'Waqtiga Hoos Lagu Filayo',
    'Distance': 'Masaafada',
    'km away': 'km meelahan ka fog',
    'mins': 'dq',

    // Timeline Screen
    'Response Timeline': 'Jadwalka Jawaabta',
    'SOS Sent': 'SOS La Diray',
    'Request Received': 'Codsiga La Helay',
    'Unit Dispatched': 'Gaari Loo Diray',
    'On the Way': 'Socda',
    'Team Arrived': 'Kooxda Soo Gaaray',
    'Incident Resolved': 'Dhibaatada La Xaliyay',

    // Settings Screen
    'App Settings': 'Habeeynta App-ka',
    'Customize your SmartRescue experience and preferences.':
        'Habee waaya-aragnimadaada iyo dooqyadaada SmartRescue.',
    'Display': 'Muuqaalka',
    'Theme and visual preferences': 'Dooqyada muuqaalka iyo midabka',
    'Dark Mode': 'Habka Madow',
    'Optimize for low-light environments': 'U habee meelaha iftiinka yar',
    'Help & Support': 'Caawinaad & Taageero',
    'Get help and report issues': 'Hel caawinaad oo sheeg dhibaatooyinka',
    'Contact Support': 'La Xiriir Taageerada',
    'Notification Settings': 'Habeeynta Ogeysiisyada',
    'Manage alerts and sound preferences':
        'Maamul ogeysiisyada iyo dooqyada codka',
    'Enable Notifications': 'Daar Ogeysiisyada',
    'Sound Alerts': 'Ogeysiisyada Codka',
    'Vibration': 'Gariirka',
    'Location Settings': 'Habeeynta Goobta (GPS)',
    'Enable GPS Location': 'Daar Goobta GPS-ka',
    'Language & Region': 'Luqadda & Gobolka',
    'LANGUAGE': 'LUQADDA',
    'Close': 'Xir',
    'Call Hotline': 'Wac Khadka Tooska ah',
    'WhatsApp Us': 'Nagala soo xiriir WhatsApp',
    'Email Support': 'Taageerada Email-ka',
    'Submit Report': 'Gudbi Warbixinta',
    'Report Problem': 'Sheeg Dhibaato',
    '12-hour (AM/PM)': '12-Saac (AM/PM)',
    '24-hour': '24-Saac',
    'Dark Mode Enabled': 'Habka Madow waa la daaray',
    'Dark Mode Disabled': 'Habka Madow waa la damiyay',
    'Language updated to 🇬🇧 English': 'Luqadda waxaa loo beddelay English',
    'Language updated to 🇸🇴 Somali': 'Luqadda waxaa loo beddelay Somali',
    'Language updated to 🇸🇦 Arabic': 'Luqadda waxaa loo beddelay Arabic',
    'Failed to update language': 'Waa uu guuldareystay cusbooneysiinta luqadda',
    'Chat with our support team': 'La sheekeyso kooxdayada taageerada',
    'Browse common questions and answers': 'Eeg su\'aalaha iyo jawaabaha caanka ah',
    'Submit a bug or technical issue': 'Guji si aad u gudbiso cillad farsamo',
    'Important updates and status alerts': 'Cusbooneysiinta muhiimka ah iyo ogeysiisyada heerka',
    'Audible dispatch notifications': 'Ogeysiisyada codka ee dirista',
    'Haptic feedback on alerts': 'Gariirka ogeysiisyada',
    'Critical fire and rescue alerts - always on': 'Ogeysiisyada dab-dambiska iyo gurmadka - had iyo jeer shidma',
    'GPS, live tracking, and location permissions': 'GPS-ka, la-socoshada tooska ah, iyo rukhsadaha goobta',
    'Core feature for emergency dispatch': 'Habka ugu muhiimsan ee gurmadka degdegga ah',
    'Share Live Location During SOS': 'La wadaag Goobta Tooska ah inta lagu jiro SOS',
    'Stream real-time assets to rescuers': 'U soo dir goobtaada tooska ah gurmadka',
    'Locale, date, and time preferences': 'Dooqyada luqadda, taariikhda, iyo waqtiga',
    'DATE FORMAT': 'HABKA TAARIIKHTA',
    'TIME FORMAT': 'HABKA WAQTIGA',
    'Our response team is available 24/7. Choose an option below to reach us.': 'Kooxdeena gurmadka waxay diyaar u tay 24/7. Dooro doorashooyinka hoose si aad noola soo xiriirto.',
    'Experiencing a technical issue or bug? Let us know so we can fix it.': 'Maysay la kulantay cillad farsamo? Nala wadaag si aan u saxno.',
    'ISSUE TYPE': 'NOOCA CILLADDA',
    'DESCRIPTION': 'FAAHFAAHINTA',
    'Please describe the problem in detail...': 'Fadlan si faahfaahsan u sharax dhibaatada...',
    'Select category...': 'Dooro nooca...',
    'GPS/Location not working': 'GPS/Goobta oo aan shaqaynayn',
    'App crashed/froze': 'App-ka oo xirmay/istaagay',
    'Display/Layout issue': 'Cillad dhanka muuqaalka ah',
    'Other technical issue': 'Cillad kale oo farsamo',
    'Please select a category first': 'Fadlan horta dooro nooca cilladda',
    'Please enter a description of the problem': 'Fadlan qor faahfaahinta dhibaatada',
    'Report submitted successfully! Thank you.': 'Warbixinta si guul leh ayaa loo gudbiyay! Waad ku mahadsan tahay.',
    'How do I trigger an SOS?': 'Sideen u diraa SOS-ka?',
    'Just press and hold the giant SOS button on your dashboard for 3 seconds, or tap it once to see options.': 'Kaliya ku cadai badhanka weyn ee SOS ee ku yaala xaruntaada muddo 3 sekan ah, ama hal mar taabo si aad u aragto dooqyada.',
    'Is my location shared instantly?': 'Goobtayda miyaa toos loo wadaagaa daqiiqadaas?',
    'Yes, the moment you activate SOS, your GPS coordinates are sent directly to the nearest dispatch unit.': 'Haa, isla marka aad hawlgaliso SOS-ka, xogtaada GPS-ka waxaa toos loogu diraa kooxda kuugu dhow ee gurmadka.',
    'Can I cancel a false alarm?': 'Ma baajin karaa digniin khaldan?',
    'Yes. If you trigger it by accident, press the "Cancel SOS" button on the tracking screen within 15 seconds.': 'Haa. Haddii aad si lama filaan ah u riixdo, taabo badhanka "Jooji SOS" ee shaashadda la-socodka 15 ilbiriqsi gudahood.',
    'How does Dark Mode help?': 'Sidee ayuu ii caawinayaa Habka Madow?',
    'Dark mode reduces screen glare in low-light environments, keeping you covert and saving your device battery during an emergency.': 'Habka madow wuxuu yareeyaa iftiinka shaashadda ee meelaha mugdiga ah, isagoo ku qarinaya oo badbaadinaya batteriga qalabkaaga inta lagu jiro xaalad degdeg ah.',

    // Community Rescue Screen
    'Community Rescue': 'Gurmadka Bulshada',
    'Active Volunteer Force': 'Ciidanka Gurmadka ee Firfircoon',
    'Local Heroes Needed': 'Geesiyaal Maxalli ah ayaa Loo Baahan Yahay',
    'ON DUTY': 'SHAQADA KU JIRA',
    'Thank you for serving the Mogadishu community! You can now view active community rescue incidents and offer support.': 'Waad ku mahadsan tahay u adeegida bulshada Muqdisho! Hadda waad arki kartaa xaaladaha gurmadka oo gacan ayaad ka geysan kartaa.',
    'Join the community rescue force and help neighbors in need during local emergencies.': 'Ku soo biir ciidanka gurmadka bulshada si aad u caawiso deriska xilliyada xaaladaha degdega ah.',
    'Leave Force': 'Ka Bax Ciidanka',
    'Join as Volunteer': 'Isu Qor Iskaa-Wax-u-Qabso',
    'Nearby Incidents': 'Dhacdooyinka Ku Dhow',
    'No Active Incidents': 'Ma Jiro Xaalado Degdeg ah',
    'The community is currently safe. Thank you!': 'Bulshada hadda waa nabad. Waad mahadsan tahay!',
    'Post Alert': 'Dir Ogeysiis',
    'Please write a brief description': 'Fadlan qor faahfaahin kooban',
    'Alert posted successfully! Nearby volunteers can see it now. 🚨': 'Ogeysiiska waa la diray! Gurmadka kale ayaa arki kara. 🚨',
    'Failed to send': 'Waa uu guuldareystay dirista',
    'Failed to post alert': 'Waa uu guuldareystay dirista ogeysiiska',
    'Unknown time': 'Waqti aan la garanayn',
    'Unknown': 'Aan la garanayn',
    'Emergency': 'Xaalad Degdeg ah',
    'Victim Contact:': 'Xiriirka Dhibbanaha:',
    'Anonymous': 'Qof Aan La Garanayn',
    'No phone': 'Taleefan ma jiro',
    'Description:': 'Faahfaahin:',
    'No details provided.': 'Wax faahfaahin ah lama bixin.',
    'Reported on': 'La soo sheegay',
    'Evidence Attachment:': 'Sawirka Caddaynta:',
    'Incident Location:': 'Goobta Dhacdada:',
    'Navigate There': 'Ku Xidh Khariidada',
    'Emergency reported, awaiting assistance details.': 'Xaalad degdeg ah ayaa lasoo sheegay, waxaa la sugayaa faahfaahinta.',
    'Distance unknown': 'Masaafo aan la garanayn',
    'Description / Location details:': 'Faahfaahinta Goobta / Dhacdada:',
    'Enter incident details, landmarks, or help needed...': 'Geli faahfaahinta dhacdada ama caawimada loo baahan yahay...',
    'Cancel Help': 'Jooji Gurmadka',
    'I Can Help': 'Waan Caawin Karaa',
    'View Details': 'Arag Faahfaahinta',
    'You are responding to this alert': 'Waa aad ka jawaabtay ogeysiiskan',

    // Live Alerts Screen
    'Live Alerts': 'Ogeysiisyada Tooska ah',
    'Your emergency is being tracked': 'Xaaladda degdegga ah waa la raacayaa',
    'No active emergencies': 'Ma jiro xaalado degdeg ah',
    'Alert Progress': 'Horumarinta Ogeysiiska',
    'NOW': 'HADDA',
    'Assigned Responder': 'Gurmadkii La Xilsaaray',
    'Rescue Operator': 'Hawlwadeen Gurmad',
    'No Active Alerts': 'Ma Jiro Ogeysiis Firfircoon',
    'When you send an SOS, live updates will appear here in real time.': 'Markaad dirto SOS, cusbooneysiinta tooska ah ayaa halkan ku muuqan doonta.',
    'Go to SOS tab to activate': 'Tag tabka SOS si aad u hawlgeliso',
    'Awaiting Response': 'Sugaya Jawaab',
    'Your SOS has been broadcasted. Dispatching team...': 'SOS-kaaga waa la baahiyay. Kooxda waa la dirayaa...',
    'Responder Assigned': 'Gurmad La Xilsaaray',
    'A rescue unit has accepted your emergency request.': 'Koox gurmad ah ayaa aqbashay codsigaaga degdegga ah.',
    'Rescue En Route': 'Gurmadku Socda',
    'Rescue team is heading to your location right now.': 'Kooxda gurmadku hadda ayay u socotaa goobtagaaga.',
    'Rescuer Arrived': 'Gurmadkii Soo Gaaray',
    'The rescue team has arrived at your location.': 'Kooxda gurmadku waxay soo gaartay goobtagaaga.',
    'Request Completed': 'Codsigii La Dhammaystay',
    'Your emergency request has been successfully resolved.': 'Codsigaaga degdegga ah si guul leh ayaa loo xaliyay.',
    'SOS Active': 'SOS Firfircoon',
    'Emergency signal is active.': 'Calaamadda degdegga ah waa firfircoon tahay.',
    'SOS Broadcasted': 'SOS Waa La Baahiyay',
    'Emergency signal sent to rescue center': 'Calaamadda degdegga ah waxaa loo diray xarunta gurmadka',
    'Request Accepted': 'Codsigii La Aqbalay',
    'Rescue operator acknowledged your request': 'Hawlwadeenka gurmadku wuxuu aqbalay codsigaaga',
    'A rescue unit has been assigned to you': 'Koox gurmad ah ayaa laguu xilsaaray',
    'Ambulance is on the way to your location': 'Baabuurka caafimaadku wuxuu u socday goobtagaaga',
    'Emergency team has reached your location': 'Kooxda degdegga ah waxay gaartay goobtagaaga',

    // Response Timeline Screen
    'The issue has been closed successfully.': 'Arrintu si guul leh ayaa loo xirxiray.',
    'Assigned responder is currently with you.': 'Gurmadkii la xilsaaray hadda ayuu kula jooga.',
    'Rescue On The Way': 'Gurmadku Socda',
    'Rescue team is heading to your location.': 'Kooxda gurmadku waxay u socotaa goobtagaaga.',
    'Responder Dispatched': 'Gurmad La Diray',
    'Dispatch center has acknowledged your SOS.': 'Xarunta diritaanku waxay aqbashay SOS-kaaga.',
    'SOS Transmitted': 'SOS Waa La Diray',
    'Awaiting dispatcher verification.': 'Sugaya xaqiijinta xarunta diritaanka.',
    'Phone number copied to clipboard!': 'Numberka telefoonka waa la koobiyay!',

    // Online Responders Screen
    'Available emergency units nearby': 'Gurmadyada degdegga ah ee diyaarka u ah meel u dhow',
    'Rescue Units': 'Kooxaha Gurmadka',
    'Blood Donors': 'Ku-deeqayaasha Dhiigga',
    'Analytics': 'Falanqaynta',
    'No Responders Online': 'Ma jiraan dad u diyaar ah khadka',
    'Check back later for available units.': 'Mar kale hubi hadhow si aad u aragto kooxo diyaar ah.',
    'Become a Blood Donor': 'Noqo deeq-bixiye dhiig',
    'Register in Medical ID to help save lives': 'Isu qor Aqoonsiga Caafimaadka si aad u badbaadiso nolosha',
    'No Blood Donors Yet': 'Weli ma jiraan ku-deeqayaal dhiig',
    'Be the first to volunteer!\nRegister via Medical Identity Card.': 'Noqo qofka ugu horreeya ee iskaa-wax-u-qabso ah!\nIsu qor Kaarka Aqoonsiga Caafimaadka.',
    'Daily Reports': 'Warbixinnada Maalinlaha ah',
    'Weekly SOS': 'SOS-ka Toddobaadlaha ah',
    'Response Performance': 'Waxqabadka Jawaab-celinta',
    'Success Rate': 'Boqolleyda Guusha',
    'Safety Score': 'Dhibcaha Badbaadada',
    'Average dispatch time': 'Celceliska waqtiga dirista',
    'Average arrival time': 'Celceliska waqtiga imaanshaha',
    'Unknown Responder': 'Gurmad aan la aqoon',
    'No Unit': 'Koox la\'aan',
    'Call Responder': 'Wac Gurmadka',
    'Copy Phone Number': 'Koobiyeey lambarka taleefanka',

    // Community Rescue Screen Extensions
    'Congratulations! You joined the Community Rescue Force! 🎉': 'Hambalyo! Waxaad ku biirtay Ciidanka Gurmadka Bulshada! 🎉',
    'You have left the Volunteer Force.': 'Waxaad ka baxday Ciidanka Iskaa-wax-u-qabsada.',
    'Thank you! Your help offer has been registered. 👍': 'Waad ku mahadsan tay! Yaboohaada caawimo waa la diiwaangeliyey. 👍',
    'You have cancelled your response.': 'Waxaad joojisay jawaab-celintaada.',
    'Post Community Alert': 'Gudbi Ogeysiiska Bulshada',
    'Select Alert Type:': 'Dooro Nooca Ogeysiiska:',
    'Please join the Volunteer Force to respond!': 'Fadlan ku biir Ciidanka Iskaa-wax-u-qabsada si aad uga jawaabto!',
    'Assisted by': 'Waxaa caawiyay',
    'another volunteer': 'iskaa-wax-u-qabso kale',
    'Police': 'Boolis',
    'Missing Person': 'Qof Maqan',
    'm away': 'm meelahan ka fog',
    'Failed to load incidents. Please pull to refresh.': 'Waa uu guuldareystay soo rarista dhacdooyinka. Fadlan kor u jiid si aad u cusbooneysiiso.',
    'Failed to update status': 'Waa uu guuldareystay cusbooneysiinta xaaladda',
    'Connection error. Please try again.': 'Cillad xiriir. Fadlan isku day markale.',
    'Failed to update response': 'Waa uu guuldareystay cusbooneysiinta jawaabta',

    // Incident Description Screen
    'Incident Description': 'Faahfaahinta Dhacdada',
    'Describe the Incident': 'Sharax Dhacdada',
    'Please provide clear, concise details about the current emergency. This information will be sent directly to the rescue team.': 'Fadlan bixi faahfaahin cad oo kooban oo ku saabsan xaaladda degdegga ah. Macluumaadkan waxaa toos loogu diri doonaa kooxda gurmadka.',
    'Type critical information here (e.g. number of injured, visible hazards, specific entry points)...': 'Halkan ku qor macluumaadka muhiimka ah (tusaale, tirada dadka dhaawacmay, khataraha muuqda, meelaha laga soo galo)...',
    'Save & Return to Dashboard': 'Keydi & Ku Noqo Xarunta',
    'Incident Description Saved!': 'Faahfaahinta Dhacdada Waa La Keydiyay!',

    // Evidence Photo Screen
    'Attach Evidence': 'Ku Dar Caddayn',
    'Attach Photo Evidence': 'Ku Dar Caddayn Sawir ah',
    'Capture or upload an image of the emergency scene. This helps responders assess the situation before arrival.': 'Ka qaad ama soo geli sawirka goobta xaaladda degdegga ah. Tani waxay caawinaysaa kooxda gurmadka inay qiimeeyaan xaaladda ka hor inta aysan imaan.',
    'No Image Attached': 'Ma jiro sawir ku lifaaqan',
    'Take a photo or upload from gallery': 'Ka qaad sawir ama ka soo geli gallery-ga',
    'Upload from Gallery': 'Ka soo geli Gallery-ga',

    // Map Screen Extended
    'LIVE': 'TOOS',
    'LOCATION': 'GOOBTA',
    'Fix Location': 'Hagaaji Goobta',
    'Auto-Track': 'La-socod Toos ah',
    'Emergency Responder': 'Gurmadka Degdegga ah',
    'Cancel Request?': 'Jooji Codsiga?',
    'Are you sure you want to cancel this emergency SOS request?': 'Ma hubtaa inaad rabto inaad joojiso codsigan SOS?',
    'No, Keep Active': 'Maya, Sii Wad',
    'Yes, Cancel': 'Haa, Jooji',
    'Finding Emergency Unit': 'Raadinta Kooxda Gurmadka',
    'Calculating\u2026': 'Xisaabinaya...',
    'Arriving now': 'Hadda ayuu imaanayaa',
    'Satellite': 'Dayaxa',
    '3D Terrain': 'Dhulka 3D',

    // Settings Screen - Toggle SnackBars
    'Notifications Enabled': 'Ogeysiisyada waa la Hawlgeliyey',
    'Notifications Disabled': 'Ogeysiisyada waa la Damiyay',
    'Vibration Enabled': 'Gariirka waa la Hawlgeliyey',
    'Vibration Disabled': 'Gariirka waa la Damiyay',
    'GPS Tracking Enabled': 'La-socoshada GPS waa la Hawlgeliyey',
    'GPS Tracking Disabled': 'La-socoshada GPS waa la Damiyay',
    'Live Location Sharing Enabled': 'Wadaagista Goobta Tooska ah waa la Hawlgeliyey',
    'Live Location Sharing Disabled': 'Wadaagista Goobta Tooska ah waa la Damiyay',
    'Location History Saved': 'Taariikhda Goobta waa la Keydinayaa',
    'Location History Disabled': 'Taariikhda Goobta waa la Damiyay',
    'Failed to toggle notifications': 'Waa uu guuldareystay beddelista ogeysiisyada',
    'Failed to toggle vibration': 'Waa uu guuldareystay beddelista gariirka',
    'Failed to toggle GPS Tracking': 'Waa uu guuldareystay beddelista la-socoshada GPS',
    'Failed to toggle live location sharing': 'Waa uu guuldareystay beddelista wadaagista goobta',
    'Failed to toggle location history': 'Waa uu guuldareystay beddelista taariikhda goobta',
    'Manage': 'Maamul',
    'Location Permission Control': 'Maamulka Rukhsadda Goobta',
    'Manage browser GPS permissions': 'Maamul rukhsadaha GPS-ka ee browser-ka',
  };

  // ─── Arabic Translations ───────────────────────────────────────────────────
  static const Map<String, String> _ar = {
    // Navigation & Drawer
    'Dashboard': 'لوحة التحكم',
    'Medical ID': 'الهوية الطبية',
    'Contacts': 'جهات الاتصال',
    'History': 'السجل',
    'My Account': 'حسابي',
    'Settings': 'الإعدادات',
    'Sign Out': 'تسجيل الخروج',
    'MAIN': 'الرئيسية',
    'ACCOUNT': 'الحساب',
    'EDIT PROFILE PICTURE': 'تعديل الصورة',
    'SOS': 'استغاثة',
    'Map': 'الخريطة',
    'Proof': 'دليل',
    'Community': 'المجتمع',
    'More': 'المزيد',

    // Home Screen
    'Emergency Center': 'مركز الطوارئ',
    'Send SOS': 'إرسال SOS',
    'TAP ONCE TO SEND ALERT': 'اضغط مرة واحدة لإرسال التنبيه',
    'Hold to Cancel Alert': 'اضغط مطولاً للإلغاء',
    'Sending Emergency Signal...': 'جاري إرسال إشارة الطوارئ...',
    'SOS Alert Activated': 'تم تفعيل تنبيه SOS',
    'Responders are viewing your location. Stay calm.':
        'فرق الإسعاف ترى موقعك. ابق هادئاً.',
    'ACTIVE SOS': 'SOS نشط',
    'Emergency Type': 'نوع الطوارئ',
    'Medical': 'طبي',
    'Fire': 'حريق',
    'Accident': 'حادث',
    'Security': 'أمن',
    'Other': 'أخرى',
    'Cancel': 'إلغاء',
    'Cancel Request': 'إلغاء الطلب',
    'Pending': 'قيد الانتظار',
    'Accepted': 'مقبول',
    'En Route': 'في الطريق',
    'Arrived': 'وصل',
    'Completed': 'مكتمل',
    'Driver Assigned': 'تم تعيين السائق',
    'Call Driver': 'اتصل بالسائق',
    'Track on Map': 'تتبع على الخريطة',
    'View Timeline': 'عرض الجدول الزمن',
    'Emergency Contacts': 'جهات اتصال الطوارئ',
    'EMERGENCY CONTACTS': 'جهات اتصال الطوارئ',
    'Guardian network': 'شبكة الحماية',
    'TOTAL SOS SENT': 'إجمالي الاستغاثات المرسلة',
    'All time': 'طوال الوقت',
    'LAST EMERGENCY': 'آخر حالة طوارئ',
    'Most recent': 'الأحدث',
    'SELECT EMERGENCY TYPE': 'اختر نوع الطوارئ',
    'AMBULANCE': 'سيارة إسعاف',
    'Medical Emergency': 'طوارئ طبية',
    'FIRE RESCUE': 'إنقاذ من الحريق',
    'Fire & Burns': 'حرائق وحروق',
    'POLICE': 'الشرطة',
    'Security Help': 'مساعدة أمنية',
    'ACCIDENT': 'حادث',
    'Vehicle Crash': 'اصطدام مركبة',
    'ACTION GUIDE': 'دليل العمل',
    '🚑 Stay calm. Check for breathing. If bleeding, apply firm pressure. Do not move if head/neck injury suspected.': '🚑 حافظ على هدوئك. تحقق من التنفس. في حالة النزيف، اضغط بقوة. لا تحرك المصاب إذا كان هناك اشتباه في إصابة الرأس/الرقبة.',
    '🚒 Evacuate immediately. Stay low under smoke. Do not open hot doors. Dial emergency services immediately.': '🚒 إخلاء المكان على الفور. ابق منخفضاً تحت الدخان. لا تفتح الأبواب الساخنة. اتصل بخدمات الطوارئ على الفور.',
    '👮 Seek immediate shelter. Lock doors and windows. Stay quiet and turn off lights. Wait for police arrival.': '👮 ابحث عن مأوى على الفور. أغلق الأبواب والنوافذ. ابق هادئاً وأطفئ الأنوار. انتظر وصول الشرطة.',
    '🚗 Pull over to a safe area. Turn on hazard lights. Check for injuries. Do not move severely injured persons unless necessary.': '🚗 توقف في منطقة آمنة. قم بتشغيل أضواء التحذير. تحقق من وجود إصابات. لا تحرك الأشخاص المصابين بجروح خطيرة إلا عند الضرورة.',
    '🚨 Stay calm. Check for safety. Report location immediately to emergency responders.': '🚨 حافظ على هدوئك. تحقق من السلامة. أبلغ عن موقعك فوراً لفرق الاستجابة للطوارئ.',
    'GPS ACCURACY': 'دقة GPS',
    '📡 Good signal': '📡 إشارة جيدة',
    'Safety: Good': 'الأمان: جيد',
    'GPS Good': 'GPS جيد',
    'EMERGENCY BROADCAST ACTIVE': 'بث الطوارئ نشط',
    'TAP BUTTON TO TRIGGER SOS': 'انقر على الزر لتفعيل SOS',
    'Online': 'متصل',
    'Hello': 'مرحباً',
    'User': 'مستخدم',
    'RESPONSE TIMELINE': 'الجدول الزمني للاستجابة',
    'Emergency signal broadcast': 'بث إشارة الطوارئ',
    'Dispatched': 'تم الإرسال',
    'Dispatch center notified': 'تم إخطار مركز الإرسال',
    'Team Assigned': 'تم تعيين الفريق',
    'Rescue unit selected': 'تم اختيار وحدة الإنقاذ',
    'On The Way': 'في الطريق',
    'Team heading to location': 'الفريق متجه إلى الموقع',
    'Team on scene': 'الفريق في الموقع',
    'Emergency successfully resolved': 'تم حل حالة الطوارئ بنجاح',
    'No contacts': 'لا توجد جهات اتصال',
    'contacts': 'جهات اتصال',

    // Contacts Screen
    'GUARDIAN NETWORK': 'شبكة الحماية',
    'Add Contact': 'إضافة جهة اتصال',
    'No emergency contacts yet.': 'لا توجد جهات اتصال طوارئ بعد.',
    'Add contacts to notify loved ones in an emergency.':
        'أضف جهات اتصال لإخطار أحبائك في حالات الطوارئ.',
    'Name': 'الاسم',
    'Phone': 'الهاتف',
    'Family Relationship': 'صلة القرابة',
    'Save': 'حفظ',
    'Edit': 'تعديل',
    'Delete': 'حذف',
    'Please fill all fields': 'يرجى ملء جميع الحقول',

    // Medical Screen
    'Medical & Safety Info': 'المعلومات الطبية والأمان',
    'Blood Type': 'فصيلة الدم',
    'Allergies': 'الحساسية',
    'Medical Conditions': 'الحالات الطبية',
    'Current Medications': 'الأدوية الحالية',
    'Emergency Notes': 'ملاحظات الطوارئ',
    'Save Changes': 'حفظ التغييرات',
    'Saving...': 'جاري الحفظ...',
    'MEDICAL RECORDS': 'السجلات الطبية',
    'Medical Identity Card': 'بطاقة الهوية الطبية',
    'Medical ID Saved Successfully!': 'تم حفظ الهوية الطبية بنجاح!',
    'Failed to save Medical ID': 'فشل حفظ الهوية الطبية',
    'Volunteer as a Blood Donor': 'التطوع كمتبرع بالدم',
    'Your name, blood group, and contact will be visible to the community in emergencies.': 'سيكون اسمك وفصيلة دمك وجهة اتصالك مرئية للمجتمع في حالات الطوارئ.',

    // History Screen
    'Rescue History': 'سجل الإنقاذ',
    'No rescue history yet.': 'لا يوجد سجل إنقاذ بعد.',
    'Your past SOS requests will appear here.':
        'ستظهر طلبات SOS السابقة هنا.',
    'Status': 'الحالة',
    'Date': 'التاريخ',
    'Type': 'النوع',
    'RECORDS': 'سجلات',
    'Details': 'تفاصيل',
    'Driver': 'سائق',
    'Waiting for responder...': 'بانتظار المستجيب...',
    'Cancel Emergency?': 'إلغاء الطوارئ؟',
    'Are you sure you want to cancel this emergency request?': 'هل أنت متأكد من رغبتك في إلغاء طلب الطوارئ هذا؟',
    'NO, STAY ACTIVE': 'لا، ابق نشطًا',
    'YES, CANCEL': 'نعم، إلغاء',
    'CANCEL EMERGENCY': 'إلغاء الطوارئ',
    'TRACK DRIVER ON MAP': 'تتبع السائق على الخريطة',
    'EMERGENCY COMMAND CENTER': 'مركز قيادة الطوارئ',
    'WELCOME': 'مرحباً',

    // Notifications Screen
    'Alert Notifications': 'إشعارات التنبيه',
    'Notifications': 'الإشعارات',
    'No notifications yet.': 'لا توجد إشعارات بعد.',
    'Mark all as read': 'تحديد الكل كمقروء',
    'Delete Notification': 'حذف الإشعار',
    'Are you sure you want to delete this notification?':
        'هل أنت متأكد من رغبتك في حذف هذا الإشعار؟',
    'Notification deleted successfully!': 'تم حذف الإشعار بنجاح!',
    'Failed to delete notification': 'فشل حذف الإشعار.',
    'Error': 'خطأ',
    'No notifications': 'لا توجد إشعارات',
    'Updates about your rescue will appear here.': 'ستظهر أي تحديثات بخصوص الإنقاذ هنا.',
    'Pull down to refresh': 'اسحب لأسفل للتحديث',
    'Refresh': 'تحديث',
    'No notifications now!': 'لا توجد إشعارات الآن!',
    'Any updates will be shown here.': 'ستظهر أي تحديثات هنا.',
    'Notifications Count': 'إشعار',
    'Just now': 'الآن',
    'ago': 'منذ',
    'minutes': 'دقائق',
    'hours': 'ساعات',
    'days': 'أيام',

    // Profile Screen
    'User Settings': 'إعدادات المستخدم',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Full Name': 'الاسم الكامل',
    'Email Address': 'عنوان البريد الإلكتروني',
    'Phone Number': 'رقم الهاتف',
    'Gender': 'الجنس',
    'Date of Birth': 'تاريخ الميلاد',
    'Change Password': 'تغيير كلمة المرور',
    'Delete Account': 'حذف الحساب',
    'Current Password': 'كلمة المرور الحالية',
    'New Password': 'كلمة المرور الجديدة',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Update Profile': 'تحديث الملف الشخصي',
    'Male': 'ذكر',
    'Female': 'أنثى',
    'Manage your profile, security, and account preferences.': 'إدارة ملفك الشخصي والأمان وتفضيلات حسابك.',
    'VERIFIED USER': 'مستخدم موثق',
    'Update your personal information': 'تحديث معلوماتك الشخصية',
    'Enter full name': 'أدخل الاسم الكامل',
    'Enter phone number': 'أدخل رقم الهاتف',
    'Enter email address': 'أدخل البريد الإلكتروني',
    'All fields are required!': 'جميع الحقول مطلوبة!',
    'Name and phone are required!': 'الاسم ورقم الهاتف مطلوبان!',
    '✅ Profile updated successfully!': '✅ تم تحديث الملف الشخصي بنجاح!',
    'Failed to update profile': 'فشل تحديث الملف الشخصي',
    'Change your account password': 'تغيير كلمة مرور حسابك',
    'Enter current password': 'أدخل كلمة المرور الحالية',
    'Min. 8 characters': '8 أحرف كحد أدنى',
    'Repeat new password': 'كرر كلمة المرور الجديدة',
    'Update Password': 'تحديث كلمة المرور',
    'Please fill in all password fields!': 'يرجى ملء جميع حقول كلمة المرور!',
    'New password must be at least 8 characters!': 'يجب أن تكون كلمة المرور الجديدة 8 أحرف على الأقل!',
    'New passwords do not match!': 'كلمات المرور الجديدة غير متطابقة!',
    'Password updated successfully!': 'تم تحديث كلمة المرور بنجاح!',
    'Failed to update password': 'فشل تحديث كلمة المرور',
    'Location Info': 'معلومات الموقع',
    'Your GPS and location access status': 'حالة نظام تحديد المواقع والوصول للموقع',
    'Last Known Location': 'آخر موقع معروف',
    '✅ Location enabled successfully.': '✅ تم تمكين الموقع بنجاح.',
    'Location disabled.': 'تم تعطيل الموقع.',
    'Failed to update Location': 'فشل تحديث الموقع',
    '⚠️ GPS enabled in settings, but browser/device permission is denied.': '⚠️ تم تمكين GPS ولكن إذن الجهاز مرفوض.',
    '⚠️ GPS enabled in settings, but location services are unavailable.': '⚠️ تم تمكين GPS ولكن خدمات الموقع غير متوفرة.',
    '✅ Live location streaming enabled during SOS.': '✅ تم تمكين بث الموقع المباشر أثناء الاستغاثة.',
    'Live location streaming disabled.': 'تم تعطيل بث الموقع المباشر.',
    'Failed to update Live Location preference': 'فشل تحديث تفضيلات الموقع المباشر',
    'Danger Zone': 'منطقة الخطر',
    'Irreversible account actions': 'إجراءات الحساب غير القابلة للتراجع',
    'All your data, history, and records will be permanently removed. This action cannot be undone.': 'سيتم إزالة جميع بياناتك وسجلك نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
    'Are you absolutely sure you want to delete your account? This action cannot be undone.': 'هل أنت متأكد تمامًا من رغبتك في حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
    'Please enter your password': 'يرجى إدخال كلمة المرور الخاصة بك',
    'Failed to delete account': 'فشل حذف الحساب',

    // Map Screen
    'Live Tracking': 'التتبع المباشر',
    'Driver Location': 'موقع السائق',
    'Your Location': 'موقعك',
    'Loading map...': 'جاري تحميل الخريطة...',
    'ETA': 'وقت الوصول المتوقع',
    'Distance': 'المسافة',
    'km away': 'كم بعيداً',
    'mins': 'دق',

    // Timeline Screen
    'Response Timeline': 'الجدول الزمني للاستجابة',
    'SOS Sent': 'تم إرسال SOS',
    'Request Received': 'تم استلام الطلب',
    'Unit Dispatched': 'تم إرسال الوحدة',
    'On the Way': 'في الطريق',
    'Team Arrived': 'وصل الفريق',
    'Incident Resolved': 'تم حل الحادث',

    // Settings Screen
    'App Settings': 'إعدادات التطبيق',
    'Customize your SmartRescue experience and preferences.':
        'تخصيص تجربة وتفضيلات SmartRescue الخاصة بك.',
    'Display': 'المظهر',
    'Theme and visual preferences': 'تفضيلات السمات والمرئيات',
    'Dark Mode': 'الوضع الداكن',
    'Optimize for low-light environments': 'تحسين لبيئات الإضاءة المنخفضة',
    'Help & Support': 'المساعدة والدعم',
    'Get help and report issues': 'احصل على المساعدة وأبلغ عن المشاكل',
    'Contact Support': 'الاتصال بالدعم',
    'Notification Settings': 'إعدادات الإشعارات',
    'Manage alerts and sound preferences': 'إدارة التنبيهات وتفضيلات الصوت',
    'Enable Notifications': 'تمكين الإشعارات',
    'Sound Alerts': 'تنبيهات صوتية',
    'Vibration': 'الاهتزاز',
    'Location Settings': 'إعدادات الموقع',
    'Enable GPS Location': 'تمكين موقع GPS',
    'Language & Region': 'اللغة والمنطقة',
    'LANGUAGE': 'اللغة',
    'Close': 'إغلاق',
    'Call Hotline': 'الاتصال بالخط الساخن',
    'WhatsApp Us': 'تواصل معنا عبر واتساب',
    'Email Support': 'دعم البريد الإلكتروني',
    'Submit Report': 'إرسال التقرير',
    'Report Problem': 'الإبلاغ عن مشكلة',
    '12-hour (AM/PM)': '12 ساعة (ص/م)',
    '24-hour': '24 ساعة',
    'Dark Mode Enabled': 'تم تفعيل الوضع الداكن',
    'Dark Mode Disabled': 'تم إلغاء الوضع الداكن',
    'Language updated to 🇬🇧 English': 'تم تحديث اللغة إلى الإنجليزية',
    'Language updated to 🇸🇴 Somali': 'تم تحديث اللغة إلى الصومالية',
    'Language updated to 🇸🇦 Arabic': 'تم تحديث اللغة إلى العربية',
    'Failed to update language': 'فشل تحديث اللغة',
    'Chat with our support team': 'تحدث مع فريق الدعم لدينا',
    'Browse common questions and answers': 'تصفح الأسئلة والأجوبة الشائعة',
    'Submit a bug or technical issue': 'تقديم بلاغ عن خلل أو مشكلة فنية',
    'Important updates and status alerts': 'تحديثات مهمة وتنبيهات الحالة',
    'Audible dispatch notifications': 'إشعارات الإرسال المسموعة',
    'Haptic feedback on alerts': 'ردود الفعل اللمسية على التنبيهات',
    'Critical fire and rescue alerts - always on': 'تنبيهات الحريق والإنقاذ الحرجة - تعمل دائمًا',
    'GPS, live tracking, and location permissions': 'نظام تحديد المواقع العالمي (GPS) والتتبع المباشر وأذونات الموقع',
    'Core feature for emergency dispatch': 'ميزة أساسية لإرسال حالات الطوارئ',
    'Share Live Location During SOS': 'مشاركة الموقع المباشر أثناء استغاثة SOS',
    'Stream real-time assets to rescuers': 'بث الموقع المباشر للمنقذين',
    'Locale, date, and time preferences': 'تفضيلات اللغة والتاريخ والوقت',
    'DATE FORMAT': 'صيغة التاريخ',
    'TIME FORMAT': 'صيغة الوقت',
    'Our response team is available 24/7. Choose an option below to reach us.': 'فريق الاستجابة لدينا متاح 24/7. اختر خياراً أدناه للوصول إلينا.',
    'Experiencing a technical issue or bug? Let us know so we can fix it.': 'هل تواجه مشكلة فنية أو خلل؟ أخبرنا حتى نتمكن من إصلاحه.',
    'ISSUE TYPE': 'نوع المشكلة',
    'DESCRIPTION': 'الوصف',
    'Please describe the problem in detail...': 'يرجى وصف المشكلة بالتفصيل...',
    'Select category...': 'اختر الفئة...',
    'GPS/Location not working': 'نظام تحديد المواقع/الموقع لا يعمل',
    'App crashed/froze': 'تعطل/تجمد التطبيق',
    'Display/Layout issue': 'مشكلة في العرض/التصميم',
    'Other technical issue': 'مشكلة فنية أخرى',
    'Please select a category first': 'يرجى اختيار الفئة أولاً',
    'Please enter a description of the problem': 'يرجى إدخال وصف للمشكلة',
    'Report submitted successfully! Thank you.': 'تم تقديم التقرير بنجاح! شكرًا لك.',
    'How do I trigger an SOS?': 'كيف يمكنني تفعيل استغاثة SOS؟',
    'Just press and hold the giant SOS button on your dashboard for 3 seconds, or tap it once to see options.': 'ما عليك سوى الضغط مع الاستمرار على زر SOS العملاق في لوحة التحكم الخاصة بك لمدة 3 ثوانٍ، أو النقر عليه مرة واحدة لرؤية الخيارات.',
    'Is my location shared instantly?': 'هل تتم مشاركة موقعي على الفور؟',
    'Yes, the moment you activate SOS, your GPS coordinates are sent directly to the nearest dispatch unit.': 'نعم، في اللحظة التي تقوم فيها بتفعيل SOS، يتم إرسال إحداثيات GPS الخاصة بك مباشرة إلى أقرب وحدة إرسال.',
    'Can I cancel a false alarm?': 'هل يمكنني إلغاء الإنذار الخاطئ؟',
    'Yes. If you trigger it by accident, press the "Cancel SOS" button on the tracking screen within 15 seconds.': 'نعم. إذا قمت بتفعيله عن طريق الخطأ، فاضغط على زر "إلغاء SOS" في شاشة التتبع في غضون 15 ثانية.',
    'How does Dark Mode help?': 'كيف يساعد الوضع الداكن؟',
    'Dark mode reduces screen glare in low-light environments, keeping you covert and saving your device battery during an emergency.': 'يقلل الوضع الداكن من توهج الشاشة في البيئات ذات الإضاءة المنخفضة، مما يحافظ على سرية هويتك ويوفر بطارية جهازك أثناء حالة الطوارئ.',

    // Live Alerts Screen
    'Live Alerts': 'التنبيهات المباشرة',
    'Your emergency is being tracked': 'يتم تتبع حالة الطوارئ الخاصة بك',
    'No active emergencies': 'لا توجد حالات طوارئ نشطة',
    'Alert Progress': 'تقدم التنبيه',
    'NOW': 'الآن',
    'Assigned Responder': 'المستجيب المعين',
    'Rescue Operator': 'مشغل الإنقاذ',
    'No Active Alerts': 'لا توجد تنبيهات نشطة',
    'When you send an SOS, live updates will appear here in real time.': 'عند إرسال SOS، ستظهر التحديثات المباشرة هنا في الوقت الفعلي.',
    'Go to SOS tab to activate': 'انتقل إلى تبويب SOS للتفعيل',
    'Awaiting Response': 'في انتظار الرد',
    'Your SOS has been broadcasted. Dispatching team...': 'تم بث SOS الخاص بك. جاري إرسال الفريق...',
    'Responder Assigned': 'تم تعيين المستجيب',
    'A rescue unit has accepted your emergency request.': 'قبلت وحدة إنقاذ طلب الطوارئ الخاص بك.',
    'Rescue En Route': 'الإنقاذ في الطريق',
    'Rescue team is heading to your location right now.': 'فريق الإنقاذ في طريقه إلى موقعك الآن.',
    'Rescuer Arrived': 'وصل المنقذ',
    'The rescue team has arrived at your location.': 'وصل فريق الإنقاذ إلى موقعك.',
    'Request Completed': 'اكتمل الطلب',
    'Your emergency request has been successfully resolved.': 'تم حل طلب الطوارئ الخاص بك بنجاح.',
    'SOS Active': 'SOS نشط',
    'Emergency signal is active.': 'إشارة الطوارئ نشطة.',
    'SOS Broadcasted': 'تم بث SOS',
    'Emergency signal sent to rescue center': 'تم إرسال إشارة الطوارئ إلى مركز الإنقاذ',
    'Request Accepted': 'تم قبول الطلب',
    'Rescue operator acknowledged your request': 'أقر مشغل الإنقاذ بطلبك',
    'A rescue unit has been assigned to you': 'تم تعيين وحدة إنقاذ لك',
    'Ambulance is on the way to your location': 'السيارة الإسعافية في طريقها إلى موقعك',
    'Emergency team has reached your location': 'وصل فريق الطوارئ إلى موقعك',

    // Response Timeline Screen
    'The issue has been closed successfully.': 'تم إغلاق المشكلة بنجاح.',
    'Assigned responder is currently with you.': 'المستجيب المعين معك حالياً.',
    'Rescue On The Way': 'الإنقاذ في الطريق',
    'Rescue team is heading to your location.': 'فريق الإنقاذ في طريقه إلى موقعك.',
    'Responder Dispatched': 'تم إرسال المستجيب',
    'Dispatch center has acknowledged your SOS.': 'أقر مركز الإرسال بـ SOS الخاص بك.',
    'SOS Transmitted': 'تم إرسال SOS',
    'Awaiting dispatcher verification.': 'في انتظار تحقق المرسل.',
    'Phone number copied to clipboard!': 'تم نسخ رقم الهاتف!',

    // Online Responders Screen
    'Available emergency units nearby': 'وحدات الطوارئ المتاحة القريبة',
    'Rescue Units': 'وحدات الإنقاذ',
    'Blood Donors': 'المتبرعون بالدم',
    'Analytics': 'التحليلات',
    'No Responders Online': 'لا يوجد مستجيبون متصلون',
    'Check back later for available units.': 'يرجى التحقق لاحقًا لمعرفة الوحدات المتاحة.',
    'Become a Blood Donor': 'كن متبرعاً بالدم',
    'Register in Medical ID to help save lives': 'سجل في الهوية الطبية للمساعدة في إنقاذ الأرواح',
    'No Blood Donors Yet': 'لا يوجد متبرعون بالدم بعد',
    'Be the first to volunteer!\nRegister via Medical Identity Card.': 'كن أول من يتطوع!\nسجل عبر بطاقة الهوية الطبية.',
    'Daily Reports': 'التقارير اليومية',
    'Weekly SOS': 'نداءات الاستغاثة الأسبوعية',
    'Response Performance': 'أداء الاستجابة',
    'Success Rate': 'معدل النجاح',
    'Safety Score': 'درجة الأمان',
    'Average dispatch time': 'متوسط وقت الإرسال',
    'Average arrival time': 'متوسط وقت الوصول',
    'Unknown Responder': 'مستجيب غير معروف',
    'No Unit': 'لا توجد وحدة',
    'Call Responder': 'اتصل بالمستجيب',
    'Copy Phone Number': 'نسخ رقم الهاتف',

    // Community Rescue Screen
    'Community Rescue': 'الإنقاذ المجتمعي',
    'Active Volunteer Force': 'قوة المتطوعين النشطة',
    'Local Heroes Needed': 'مطلوب أبطال محليين',
    'ON DUTY': 'في الخدمة',
    'Thank you for serving the Mogadishu community! You can now view active community rescue incidents and offer support.': 'شكراً لخدمتك مجتمع مقديشو! يمكنك الآن عرض حوادث الإنقاذ المجتمعي النشطة وتقديم الدعم.',
    'Join the community rescue force and help neighbors in need during local emergencies.': 'انضم إلى قوة الإنقاذ المجتمعي وساعد الجيران المحتاجين أثناء حالات الطوارئ المحلية.',
    'Leave Force': 'مغادرة القوة',
    'Join as Volunteer': 'الانضمام كمتطوع',
    'Nearby Incidents': 'الحوادث القريبة',
    'No Active Incidents': 'لا توجد حوادث نشطة',
    'The community is currently safe. Thank you!': 'المجتمع آمن حالياً. شكراً لك!',
    'Post Alert': 'نشر تنبيه',
    'Please write a brief description': 'يرجى كتابة وصف موجز',
    'Alert posted successfully! Nearby volunteers can see it now. 🚨': 'تم نشر التنبيه بنجاح! يمكن للمتطوعين القريبين رؤيته الآن. 🚨',
    'Failed to send': 'فشل الإرسال',
    'Failed to post alert': 'فشل نشر التنبيه',
    'Unknown time': 'وقت غير معروف',
    'Unknown': 'غير معروف',
    'Emergency': 'طوارئ',
    'Victim Contact:': 'الاتصال بالضحية:',
    'Anonymous': 'مجهول',
    'No phone': 'لا يوجد هاتف',
    'Description:': 'الوصف:',
    'No details provided.': 'لم يتم تقديم تفاصيل.',
    'Reported on': 'تم الإبلاغ في',
    'Evidence Attachment:': 'مرفق الدليل:',
    'Incident Location:': 'موقع الحادث:',
    'Navigate There': 'التوجيه إلى هناك',
    'Emergency reported, awaiting assistance details.': 'تم الإبلاغ عن حالة طوارئ، بانتظار تفاصيل المساعدة.',
    'Distance unknown': 'المسافة غير معروفة',
    'Description / Location details:': 'تفاصيل الوصف / الموقع:',
    'Enter incident details, landmarks, or help needed...': 'أدخل تفاصيل الحادث أو المعالم أو المساعدة المطلوبة...',
    'Cancel Help': 'إلغاء المساعدة',
    'I Can Help': 'أستطيع المساعدة',
    'View Details': 'عرض التفاصيل',
    'You are responding to this alert': 'أنت تستجيب لهذا التنبيه',
    'Congratulations! You joined the Community Rescue Force! 🎉': 'تهانينا! لقد انضممت إلى قوة الإنقاذ المجتمعي! 🎉',
    'You have left the Volunteer Force.': 'لقد غادرت قوة المتطوعين.',
    'Thank you! Your help offer has been registered. 👍': 'شكراً لك! تم تسجيل عرض المساعدة الخاص بك. 👍',
    'You have cancelled your response.': 'لقد قمت بإلغاء استجابتك.',
    'Post Community Alert': 'نشر تنبيه مجتمعي',
    'Select Alert Type:': 'اختر نوع التنبيه:',
    'Please join the Volunteer Force to respond!': 'يرجى الانضمام إلى قوة المتطوعين للاستجابة!',
    'Assisted by': 'بمساعدة',
    'another volunteer': 'متطوع آخر',
    'Police': 'الشرطة',
    'Missing Person': 'شخص مفقود',
    'm away': 'متر بعيداً',
    'Failed to load incidents. Please pull to refresh.': 'فشل تحميل الحوادث. يرجى السحب للتحديث.',
    'Failed to update status': 'فشل تحديث الحالة',
    'Connection error. Please try again.': 'خطأ في الاتصال. يرجى المحاولة مرة أخرى.',
    'Failed to update response': 'فشل تحديث الاستجابة',

    // Incident Description Screen
    'Incident Description': 'وصف الحادث',
    'Describe the Incident': 'صف الحادث',
    'Please provide clear, concise details about the current emergency. This information will be sent directly to the rescue team.': 'يرجى تقديم تفاصيل واضحة وموجزة عن حالة الطوارئ الحالية. سيتم إرسال هذه المعلومات مباشرة إلى فريق الإنقاذ.',
    'Type critical information here (e.g. number of injured, visible hazards, specific entry points)...': 'اكتب المعلومات الحيوية هنا (مثل عدد الجرحى، المخاطر المرئية، نقاط دخول محددة)...',
    'Save & Return to Dashboard': 'حفظ والعودة إلى لوحة التحكم',
    'Incident Description Saved!': 'تم حفظ وصف الحادث!',

    // Evidence Photo Screen
    'Attach Evidence': 'إرفاق دليل',
    'Attach Photo Evidence': 'إرفاق دليل بالصور',
    'Capture or upload an image of the emergency scene. This helps responders assess the situation before arrival.': 'التقط أو حمّل صورة لموقع الطوارئ. يساعد هذا المستجيبين على تقييم الوضع قبل الوصول.',
    'No Image Attached': 'لم يتم إرفاق صورة',
    'Take a photo or upload from gallery': 'التقط صورة أو حمّل من المعرض',
    'Upload from Gallery': 'تحميل من المعرض',

    // Map Screen Extended
    'LIVE': 'مباشر',
    'LOCATION': 'الموقع',
    'Fix Location': 'إصلاح الموقع',
    'Auto-Track': 'التتبع التلقائي',
    'Emergency Responder': 'مستجيب الطوارئ',
    'Cancel Request?': 'إلغاء الطلب؟',
    'Are you sure you want to cancel this emergency SOS request?': 'هل أنت متأكد من رغبتك في إلغاء طلب الاستغاثة هذا؟',
    'No, Keep Active': 'لا، استمر',
    'Yes, Cancel': 'نعم، إلغاء',
    'Finding Emergency Unit': 'البحث عن وحدة الطوارئ',
    'Calculating\u2026': 'جارٍ الحساب...',
    'Arriving now': 'يصل الآن',
    'Satellite': 'قمر صناعي',
    '3D Terrain': 'تضاريس ثلاثية الأبعاد',

    // Settings Screen - Toggle SnackBars
    'Notifications Enabled': 'تم تفعيل الإشعارات',
    'Notifications Disabled': 'تم تعطيل الإشعارات',
    'Vibration Enabled': 'تم تفعيل الاهتزاز',
    'Vibration Disabled': 'تم تعطيل الاهتزاز',
    'GPS Tracking Enabled': 'تم تفعيل تتبع GPS',
    'GPS Tracking Disabled': 'تم تعطيل تتبع GPS',
    'Live Location Sharing Enabled': 'تم تفعيل مشاركة الموقع المباشر',
    'Live Location Sharing Disabled': 'تم تعطيل مشاركة الموقع المباشر',
    'Location History Saved': 'جارٍ حفظ سجل الموقع',
    'Location History Disabled': 'تم تعطيل سجل الموقع',
    'Failed to toggle notifications': 'فشل تبديل الإشعارات',
    'Failed to toggle vibration': 'فشل تبديل الاهتزاز',
    'Failed to toggle GPS Tracking': 'فشل تبديل تتبع GPS',
    'Failed to toggle live location sharing': 'فشل تبديل مشاركة الموقع المباشر',
    'Failed to toggle location history': 'فشل تبديل سجل الموقع',
    'Manage': 'إدارة',
    'Location Permission Control': 'التحكم في إذن الموقع',
    'Manage browser GPS permissions': 'إدارة أذونات GPS للمتصفح',
  };

  /// Translate a key using the current user's language from AuthProvider.
  /// Falls back to the original key if no translation found.
  static String t(BuildContext context, String key) {
    try {
      final auth = Provider.of<AuthProvider>(context);
      final lang = auth.user?.language ?? 'en';
      if (lang == 'so') return _so[key] ?? key;
      if (lang == 'ar') return _ar[key] ?? key;
    } catch (_) {}
    return key;
  }

  /// Returns current language code from context
  static String langCode(BuildContext context) {
    try {
      final auth = Provider.of<AuthProvider>(context);
      return auth.user?.language ?? 'en';
    } catch (_) {
      return 'en';
    }
  }

  /// Returns true if current language is RTL (Arabic)
  static bool isRtl(BuildContext context) => langCode(context) == 'ar';

  /// Returns Locale for current language
  static Locale toLocale(String lang) {
    switch (lang) {
      case 'so': return const Locale('so', 'SO');
      case 'ar': return const Locale('ar', 'SA');
      default:   return const Locale('en', 'US');
    }
  }
}
